language: python
python: [2.7, 3.4, 3.5, 3.6]
install: pip install tox-travis
script:
- tox
- tox -e docs
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$(git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep CHANGES\.rst)" != "" ]]'
