language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -U pip setuptools
  - pip install -e .[tests]
script:
  - py.test tests -v
  - pip install 'typing<3.5.2' && py.test tests -v
